Repository CS-130-Winter-2024/balhalla, pull requests merged in 2024-03, with the labels that each got.

#22 Create and change arena, viking, and weapon models
  client/assets/models/SeaArena.glb
  client/assets/models/VikingBoat.glb
  client/assets/models/weapons/Axe.glb
  client/assets/models/weapons/Mjolnir.glb
  client/assets/models/weapons/Trident.glb
  client/src/game/World.jsx
Labels: enhancement

#25 Create and add pet models for the item shop
  client/assets/models/pets/Duck.glb
  client/assets/models/pets/Pig.glb
  client/assets/models/pets/Tree.glb
  client/assets/models/pets/Turtle.glb
Labels: enhancement

#26 Load models and replace ball
  client/src/constants.jsx
  client/src/game/Balls.jsx
  client/src/game/Game.jsx
  client/src/game/Models.jsx
  client/src/game/World.jsx
Labels: enhancement

#30 Upload raw models for testing
  client/assets/models/VikingGhost.glb
  client/assets/models/raw/Arena.model
  client/assets/models/raw/Axe.model
  client/assets/models/raw/Duck.model
  client/assets/models/raw/Mjolnir.model
  client/assets/models/raw/Pig.model
  client/assets/models/raw/SeaArena.model
  client/assets/models/raw/Tree.model
  client/assets/models/raw/Trident.model
  client/assets/models/raw/Turtle.model
  client/assets/models/raw/Viking.model
  client/assets/models/raw/VikingBoat.model
  client/assets/models/raw/VikingGhost.model
  client/assets/models/weapons/Axe.glb
  client/assets/models/weapons/Mjolnir.glb
  client/src/constants.jsx
Labels: enhancement

#29 Add viking ghost model and remove textures from weapons
  client/assets/models/VikingGhost.glb
  client/assets/models/weapons/Axe.glb
  client/assets/models/weapons/Mjolnir.glb
  client/src/constants.jsx
Labels: enhancement

#31 Gamestates and refactoring
  client/src/constants.jsx
  client/src/game/Balls.jsx
  client/src/game/Connection.jsx
  client/src/game/Game.jsx
  client/src/game/Models.jsx
  client/src/game/OtherPlayers.jsx
  client/src/game/Player.jsx
  constants.js
  gameServer.js
  index.js
  src/connection.js
  src/gameServer.js
  src/states/dodgeballState.js
  src/states/lobbyState.js
Labels: enhancement

#34 Animations
  client/assets/models/raw/Trident.model
  client/assets/models/weapons/Trident.glb
  client/src/constants.jsx
  client/src/game/Balls.jsx
  client/src/game/Game.jsx
  client/src/game/OtherPlayers.jsx
  client/src/game/Player.jsx
  constants.js
  src/states/dodgeballState.js
  src/states/lobbyState.js
Labels: enhancement

#35 Playermodel+documentation
  client/package-lock.json
  client/src/constants.jsx
  client/src/game/Balls.jsx
  client/src/game/Game.jsx
  client/src/game/OtherPlayers.jsx
  client/src/game/Player.jsx
  constants.js
  package-lock.json
  src/states/dodgeballState.js
  src/states/lobbyState.js
Labels: documentation, enhancement

#36 Playermodel+documentation
  constants.js
  src/gameServer.js
  src/states/dodgeballState.js
Labels: documentation

#40 small change: add game over check when players leave
  src/states/dodgeballState.js
Labels: enhancement

#41 Ishaan login - leaderboard, signup UI, and corresponding database functionality
  client/assets/textures/Background.png
  client/src/ui/UI.jsx
  client/src/ui/sample-data.json
  client/src/ui/ui.css
  db/database.cjs
  index.js
Labels: enhancement

#42 Dataflow PR
  client/assets/images/Hamter.jpg
  client/assets/images/KingKev.jpg
  client/assets/images/Panda.png
  client/assets/images/Shaq.png
  client/assets/textures/Background.png
  client/assets/textures/Parchment.png
  client/index.html
  client/src/constants.jsx
  client/src/game/Game.jsx
  client/src/game/Player.jsx
  client/src/main.jsx
  client/src/menus/TabCarousel.jsx
  client/src/menus/TabSettingsContent.jsx
  client/src/ui/UI.jsx
  client/src/ui/components/AlertWrapper.jsx
  client/src/ui/components/AvatarSelector.jsx
  client/src/ui/components/CustomAlert.jsx
  client/src/ui/components/EndScreen.jsx
  client/src/ui/components/InGameMenu.jsx
  client/src/ui/components/Instructions.jsx
  client/src/ui/components/LogWrapper.jsx
  client/src/ui/components/PlayerStats.jsx
  client/src/ui/components/Settings.jsx
  client/src/ui/components/Store.jsx
  client/src/ui/ui.css
  client/vite.config.js
  db/database.cjs
Labels: enhancement

#43 Add build instructions to README
  .gitignore
  README.md
  client/.gitignore
Labels: documentation

#44 end screen design
  client/assets/images/axe_cross.png
  client/assets/images/fire.gif
  client/assets/images/sword_cross.png
  client/src/ui/components/EndScreen.jsx
Labels: enhancement

#45 Final touches
  .gitignore
  .replit
  client/assets/images/Viking.png
  client/assets/images/axe_cross.png
  client/assets/images/fire.gif
  client/assets/images/sword_cross.png
  client/assets/models/Arena.glb
  client/assets/models/ArenaOG.glb
  client/assets/textures/BackgroundVertical.png
  client/src/constants.jsx
  client/src/game/Authentication.jsx
  client/src/game/Balls.jsx
  client/src/game/Connection.jsx
  client/src/game/Game.jsx
  client/src/game/Models.jsx
  client/src/game/OtherPlayers.jsx
  client/src/game/Player.jsx
  client/src/game/PlayerPet.jsx
  client/src/game/World.jsx
  client/src/main.jsx
  client/src/ui/UI.jsx
  client/src/ui/components/Announcer.jsx
  client/src/ui/components/AvatarSelector.jsx
  client/src/ui/components/Clock.jsx
  client/src/ui/components/EndScreen.jsx
  client/src/ui/components/InGameMenu.jsx
  client/src/ui/components/Settings.jsx
  client/src/ui/components/Store.jsx
  client/vite.config.js
  constants.js
  db/database.cjs
  index.js
  src/connection.js
  src/states/dodgeballState.js
  src/states/lobbyState.js
Labels: enhancement
